#!/bin/sh
# WAN/WG ifup: reserved prefixes stay in main table; reconnect or refresh split routes.

[ "$ACTION" = ifup ] || [ "$ACTION" = ifupdate ] || exit 0

vpname="$(uci -q get gogogo.@default[0].vpname || echo GOGOGO)"
enable=$(uci -q get gogogo.@default[0].enable)

case "$INTERFACE" in
	wan|wan6)
		/usr/sbin/gogogo pin_reserved >/dev/null 2>&1 &
		if [ "$enable" = "1" ]; then
			/usr/sbin/gogogo connect >/dev/null 2>&1 &
		else
			/usr/sbin/gogogo refresh_routes >/dev/null 2>&1 &
		fi
		;;
	"$vpname")
		/usr/sbin/gogogo pin_reserved >/dev/null 2>&1 &
		/usr/sbin/gogogo refresh_routes >/dev/null 2>&1 &
		;;
esac
